-- MySQL Script generated by MySQL Workbench
-- Sat Nov  6 12:32:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`aeropuerto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aeropuerto` (
  `codigo` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`avion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avion` (
  `modelo` VARCHAR(20) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `entrada_servicio` DATE NOT NULL,
  `marca_codigo` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  CONSTRAINT `fk_avion_marca1`
    FOREIGN KEY (`marca_codigo`)
    REFERENCES `mydb`.`marca` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_avion_marca1_idx` ON `mydb`.`avion` (`marca_codigo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`localidad` (
  `idlocalidad` INT NOT NULL,
  `nombre` VARCHAR(20) NULL DEFAULT NULL,
  `provincia_idprovincia` INT NOT NULL,
  PRIMARY KEY (`idlocalidad`),
  CONSTRAINT `fk_localidad_provincia1`
    FOREIGN KEY (`provincia_idprovincia`)
    REFERENCES `mydb`.`provincia` (`idprovincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_localidad_provincia1_idx` ON `mydb`.`localidad` (`provincia_idprovincia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `pais` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`pasajero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pasajero` (
  `viajeroFrecuente` TINYINT NOT NULL,
  `persona_dni` INT NOT NULL,
  PRIMARY KEY (`persona_dni`),
  CONSTRAINT `fk_pasajero_persona1`
    FOREIGN KEY (`persona_dni`)
    REFERENCES `mydb`.`persona` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`pasajero_has_vuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pasajero_has_vuelo` (
  `pasajero_persona_dni` INT NOT NULL,
  `vuelo_codigo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`pasajero_persona_dni`, `vuelo_codigo`),
  CONSTRAINT `fk_pasajero_has_vuelo_pasajero1`
    FOREIGN KEY (`pasajero_persona_dni`)
    REFERENCES `mydb`.`pasajero` (`persona_dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pasajero_has_vuelo_vuelo1`
    FOREIGN KEY (`vuelo_codigo`)
    REFERENCES `mydb`.`vuelo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_pasajero_has_vuelo_vuelo1_idx` ON `mydb`.`pasajero_has_vuelo` (`vuelo_codigo` ASC) VISIBLE;

CREATE INDEX `fk_pasajero_has_vuelo_pasajero1_idx` ON `mydb`.`pasajero_has_vuelo` (`pasajero_persona_dni` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `apellido` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `dni` INT NOT NULL,
  `num_calle` INT NULL DEFAULT NULL,
  `nombre_calle` VARCHAR(20) NULL DEFAULT NULL,
  `localidad_idlocalidad` INT NOT NULL,
  `provincia_idprovincia` INT NOT NULL,
  PRIMARY KEY (`dni`),
  CONSTRAINT `fk_personas_localidad1`
    FOREIGN KEY (`localidad_idlocalidad`)
    REFERENCES `mydb`.`localidad` (`idlocalidad`),
  CONSTRAINT `fk_personas_provincia1`
    FOREIGN KEY (`provincia_idprovincia`)
    REFERENCES `mydb`.`provincia` (`idprovincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_personas_localidad1_idx` ON `mydb`.`persona` (`localidad_idlocalidad` ASC) VISIBLE;

CREATE INDEX `fk_personas_provincia1_idx` ON `mydb`.`persona` (`provincia_idprovincia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`piloto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`piloto` (
  `cuil` VARCHAR(20) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `persona_dni` INT NOT NULL,
  PRIMARY KEY (`cuil`, `persona_dni`),
  CONSTRAINT `fk_piloto_persona1`
    FOREIGN KEY (`persona_dni`)
    REFERENCES `mydb`.`persona` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_piloto_persona1_idx` ON `mydb`.`piloto` (`persona_dni` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`provincia` (
  `idprovincia` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprovincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`vuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vuelo` (
  `horaFecha_partida` DATETIME NOT NULL,
  `horaFecha_llegada` DATETIME NOT NULL,
  `codigo` VARCHAR(20) NOT NULL,
  `piloto_cuil` VARCHAR(20) NOT NULL,
  `piloto_persona_dni` INT NOT NULL,
  `avion_matricula` VARCHAR(45) NOT NULL,
  `aeropuerto_codigo` VARCHAR(10) NOT NULL,
  `aeropuerto_codigo1` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_vuelo_piloto1`
    FOREIGN KEY (`piloto_cuil` , `piloto_persona_dni`)
    REFERENCES `mydb`.`piloto` (`cuil` , `persona_dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vuelo_avion1`
    FOREIGN KEY (`avion_matricula`)
    REFERENCES `mydb`.`avion` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vuelo_aeropuerto1`
    FOREIGN KEY (`aeropuerto_codigo`)
    REFERENCES `mydb`.`aeropuerto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vuelo_aeropuerto2`
    FOREIGN KEY (`aeropuerto_codigo1`)
    REFERENCES `mydb`.`aeropuerto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_vuelo_piloto1_idx` ON `mydb`.`vuelo` (`piloto_cuil` ASC, `piloto_persona_dni` ASC) VISIBLE;

CREATE INDEX `fk_vuelo_avion1_idx` ON `mydb`.`vuelo` (`avion_matricula` ASC) VISIBLE;

CREATE INDEX `fk_vuelo_aeropuerto1_idx` ON `mydb`.`vuelo` (`aeropuerto_codigo` ASC) VISIBLE;

CREATE INDEX `fk_vuelo_aeropuerto2_idx` ON `mydb`.`vuelo` (`aeropuerto_codigo1` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
